"""create initial schema

Revision ID: ef027d82d5e6
Revises:
Create Date: 2026-07-10 04:40:54.071020
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "ef027d82d5e6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "websites",
        sa.Column("domain", sa.String(length=253), nullable=False),
        sa.Column("root_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("has_email", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "has_pricing_page", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column(
            "has_careers_page", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("has_blog", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "has_contact_page", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_websites")),
    )
    op.create_index(op.f("ix_websites_domain"), "websites", ["domain"], unique=True)
    op.create_table(
        "crawl_jobs",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column("start_url", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued", "running", "completed", "failed", "cancelled", name="crawl_job_status"
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("max_pages", sa.Integer(), server_default=sa.text("20"), nullable=False),
        sa.Column("pages_crawled", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("pages_failed", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_pages BETWEEN 1 AND 100", name=op.f("ck_crawl_jobs_max_pages_range")
        ),
        sa.CheckConstraint(
            "pages_crawled >= 0", name=op.f("ck_crawl_jobs_pages_crawled_nonnegative")
        ),
        sa.CheckConstraint(
            "pages_failed >= 0", name=op.f("ck_crawl_jobs_pages_failed_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_crawl_jobs_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    op.create_index(op.f("ix_crawl_jobs_status"), "crawl_jobs", ["status"], unique=False)
    op.create_index(op.f("ix_crawl_jobs_website_id"), "crawl_jobs", ["website_id"], unique=False)
    op.create_table(
        "important_pages",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column(
            "page_type",
            sa.Enum(
                "pricing",
                "careers",
                "blog",
                "contact",
                "about",
                "docs",
                "login",
                "signup",
                "terms",
                "privacy",
                name="important_page_type",
            ),
            nullable=False,
        ),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_important_pages_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_important_pages_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_important_pages")),
        sa.UniqueConstraint(
            "website_id", "page_type", "url", name="uq_important_pages_website_type_url"
        ),
    )
    op.create_index(
        op.f("ix_important_pages_website_id"), "important_pages", ["website_id"], unique=False
    )
    op.create_table(
        "social_links",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_social_links_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_links")),
        sa.UniqueConstraint(
            "website_id", "platform", "url", name="uq_social_links_website_platform_url"
        ),
    )
    op.create_index(
        op.f("ix_social_links_website_id"), "social_links", ["website_id"], unique=False
    )
    op.create_table(
        "technologies",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 1", name=op.f("ck_technologies_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_technologies_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_technologies")),
        sa.UniqueConstraint("website_id", "name", name="uq_technologies_website_name"),
    )
    op.create_index(
        op.f("ix_technologies_website_id"), "technologies", ["website_id"], unique=False
    )
    op.create_table(
        "pages",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column("crawl_job_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("meta_description", sa.Text(), nullable=True),
        sa.Column(
            "headings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=255), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("page_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("text_preview", sa.Text(), nullable=True),
        sa.Column("fetch_error", sa.Text(), nullable=True),
        sa.Column("crawled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["crawl_job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_pages_crawl_job_id_crawl_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_pages_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pages")),
        sa.UniqueConstraint("crawl_job_id", "normalized_url", name="uq_pages_job_normalized_url"),
    )
    op.create_index(op.f("ix_pages_crawl_job_id"), "pages", ["crawl_job_id"], unique=False)
    op.create_index(op.f("ix_pages_website_id"), "pages", ["website_id"], unique=False)
    op.create_table(
        "emails",
        sa.Column("website_id", sa.UUID(), nullable=False),
        sa.Column("page_id", sa.UUID(), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["page_id"], ["pages.id"], name=op.f("fk_emails_page_id_pages"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["website_id"],
            ["websites.id"],
            name=op.f("fk_emails_website_id_websites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emails")),
        sa.UniqueConstraint("website_id", "email", name="uq_emails_website_email"),
    )
    op.create_index(op.f("ix_emails_page_id"), "emails", ["page_id"], unique=False)
    op.create_index(op.f("ix_emails_website_id"), "emails", ["website_id"], unique=False)
    op.create_table(
        "links",
        sa.Column("source_page_id", sa.UUID(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("normalized_target_url", sa.Text(), nullable=False),
        sa.Column("link_text", sa.String(length=1024), nullable=True),
        sa.Column("is_internal", sa.Boolean(), nullable=False),
        sa.Column("is_broken", sa.Boolean(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_page_id"],
            ["pages.id"],
            name=op.f("fk_links_source_page_id_pages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    )
    op.create_index(op.f("ix_links_source_page_id"), "links", ["source_page_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_links_source_page_id"), table_name="links")
    op.drop_table("links")
    op.drop_index(op.f("ix_emails_website_id"), table_name="emails")
    op.drop_index(op.f("ix_emails_page_id"), table_name="emails")
    op.drop_table("emails")
    op.drop_index(op.f("ix_pages_website_id"), table_name="pages")
    op.drop_index(op.f("ix_pages_crawl_job_id"), table_name="pages")
    op.drop_table("pages")
    op.drop_index(op.f("ix_technologies_website_id"), table_name="technologies")
    op.drop_table("technologies")
    op.drop_index(op.f("ix_social_links_website_id"), table_name="social_links")
    op.drop_table("social_links")
    op.drop_index(op.f("ix_important_pages_website_id"), table_name="important_pages")
    op.drop_table("important_pages")
    op.drop_index(op.f("ix_crawl_jobs_website_id"), table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_status"), table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
    op.drop_index(op.f("ix_websites_domain"), table_name="websites")
    op.drop_table("websites")
    postgresql.ENUM(name="important_page_type").drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name="crawl_job_status").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
